

/**App.js */
/*
    This version has a problem related to 
    notes.map( note =>
                    <li>
                        {note.content}
                    </li>
    )} 
    
    The elements generated by the map method,
    must each have a unique key.

    notes.map( note =>
        <li key={note.id}>>
            {note.content}
        </li>
    )


    react uses the key attribute of objects in an array to
    determine how to update the view generated by a component.
*/
const App = (props) => {
    const { notes } = props

    return(
        <div>
            <h1>Notes</h1>
            <ul>
                { /*<li>{notes[0].content}</li>
                <li>{notes[1].content}</li>
                <li>{notes[2].content}</li> */ 
                // We can improve the above code by generating React 
                //elements from the array objects 
                //using the map() function
                }
                
                {notes.map( note =>
                    <li key={note.id}>
                        {note.content}
                    </li>
                )} 
                {/* The above generates an array of li elements*/ }
            </ul>
        </div>
    )
}

export default App

/**index.js */
import React from 'react'
import ReactDOM from 'react-dom/client'

import App from './App'

const notes = [
    {
        id: 1,
        content: 'HTML is easy',
        date: '2019-05-30T17:30:31.098Z',
        important: true
    },
    {
        id: 2,
        content: 'Browser can execute only JavaScript',
        date: '2019-05-30T18:39:34.091Z',
        important: false
    },
    {
        id: 3,
        content: 'GET and POST are the most important methods of HTTP protocol',
        date: '2019-05-30T19:20:14.298Z',
        important: true
    }
]

ReactDOM.createRoot(document.getElementById('root')).render(
    <App notes={notes} />
)